exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
exec-once = hypridle
exec-once = sleep 1 && ~/.local/bin/wallpaper
exec-once = swayosd-server
exec-once = autotiling
exec-once = nm-applet --indicator
exec-once = blueman-applet
#exec-once = caelestia shell
exec-once = ~/.local/bin/pywalfox start
exec-once = wl-paste --watch cliphist store
exec-once = udiskie --automount --notify
exec-once = hyprswitch init
