$mainMod = SUPER
$terminal = kitty
$fileManager = yazi
$menu = ~/.local/bin/appmenu

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland
env = GDK_BACKEND,wayland,x11
env = CLUTTER_BACKEND,wayland

exec-once = hyprctl setcursor Bibata-Modern-Ice 24

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

windowrule = float on, match:class ^wallpaper-picker$
windowrule = center on, match:class ^wallpaper-picker$
windowrule = size 900 600, match:class ^wallpaper-picker$
windowrule = float on, match:class ^(floating-term)$
windowrule = center on, match:class ^(floating-term)$

windowrule = float on, match:class ^xdg-desktop-portal-gtk$
windowrule = center on, match:class ^xdg-desktop-portal-gtk$
windowrule = float on, match:class ^org.freedesktop.impl.portal.desktop.hyprland$
windowrule = center on, match:class ^org.freedesktop.impl.portal.desktop.hyprland$

windowrule = float on, match:class ^Gimp$
windowrule = center on, match:class ^Gimp$
windowrule = size (monitor_w*.8) (monitor_h*.8), match:class ^Gimp$

windowrule = float on, match:class ^steam$
windowrule = size (monitor_w*.7) (monitor_h*.8), match:class ^steam$

windowrule = float on, match:class ^pavucontrol$
windowrule = center on, match:class ^pavucontrol$
windowrule = size (monitor_w*.4) (monitor_h*.5), match:class ^pavucontrol$

windowrule = float on, match:class ^nm-connection-editor$
windowrule = center on, match:class ^nm-connection-editor$

windowrule = float on, match:class ^blueman-manager$
windowrule = center on, match:class ^blueman-manager$

windowrule = float on, match:title ^(Open File|Save As|Select a File|Choose File)(.*)$
windowrule = center on, match:title ^(Open File|Save As|Select a File|Choose File)(.*)$

windowrule = float on, match:class ^firefox$, match:title ^(About|Preferences|Bookmarks|Downloads|Save)
windowrule = center on, match:class ^firefox$, match:title ^(About|Preferences|Bookmarks|Downloads|Save)
